<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e20d8d03-efb9-4001-bce6-cda0c2cfbca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SidebarContent']/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SidebarContent > a:nth-of-type(2) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SidebarContent >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f7a07078-f0d0-47ac-8541-eeb7e2db1ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/dogs_icon.gif</value>
      <webElementGuid>e6a014ef-4b04-4d30-9630-ef7c6e16d412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContent&quot;)/a[2]/img[1]</value>
      <webElementGuid>1f63a61d-7f85-4bbf-8cf0-983a15f86e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SidebarContent']/a[2]/img</value>
      <webElementGuid>1418217e-37e6-418f-ae9e-f1d42051dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]/img</value>
      <webElementGuid>cab8c9d0-4e7e-4606-854c-d6c1d3c4aef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/dogs_icon.gif']</value>
      <webElementGuid>13ab5542-f822-4f0b-8bce-224ec7e5ff79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
